version: "3"

# References for compose
# https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# https://github.com/crazy-max/docker-cloudflared/blob/master/examples/pihole/docker-compose.yml
services:
  cloudflared:
    container_name: cloudflared
    image: jbencina/cloudflared:latest
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.20.0.3
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      DNS1: '172.20.0.3#5053'
      DNS2: 'no'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 172.20.0.2
networks:
  pihole:
    ipam:
      config:
        - subnet: 172.20.0.0/24